'use client'

import React, { useRef, useState, useEffect } from 'react'
import Link from 'next/link'
import Footer from '@/components/footer/footer'
import { cn } from '@/lib/utils'
import { ArrowUpRight, ArrowDown, Layers, Sparkles, Zap, Cpu } from 'lucide-react'

const stats = [
  { value: '50+',  label: 'Projects Shipped',  index: '01' },
  { value: '4+',   label: 'Regions Served',     index: '02' },
  { value: '100%', label: 'On-time Delivery',   index: '03' },
  { value: '8+',   label: 'Industries Covered', index: '04' },
]

const services = [
  {
    Icon: Layers,
    title: 'Website & Mobile App Development',
    description:
      'Full-stack web and mobile applications for Android & iOS — from UI/UX design through to deployment, cloud hosting, and ongoing modernisation of digital platforms.',
    index: '01',
    span: 'lg:col-span-3',
  },
  {
    Icon: Sparkles,
    title: 'AI-Powered Content',
    description:
      'UX-focused, SEO-optimised content generated by AI — conversion-ready copy tailored for your digital product, brand, and audience.',
    index: '02',
    span: 'lg:col-span-2',
  },
  {
    Icon: Zap,
    title: 'AI, Automation & CRM',
    description:
      'Intelligent chatbots, workflow automation, cybersecurity hardening, and CRM integration for web, app, and business operations.',
    index: '03',
    span: 'lg:col-span-2',
  },
  {
    Icon: Cpu,
    title: 'Robotics, Drones & Smart Systems',
    description:
      'Development and deployment of humanoid robotics, drone systems, and custom smart hardware for industrial, logistics, and commercial clients.',
    index: '04',
    span: 'lg:col-span-3',
  },
]

const milestones = [
  {
    year: '2022',
    title: 'Founded in Kuwait City',
    desc: 'A small team of senior engineers and designers united around one goal: build exceptional digital products for the boldest ideas.',
  },
  {
    year: '2023',
    title: 'First 20 products shipped',
    desc: 'Expanded to web, mobile, AI, and CRM — delivering for clients across the GCC and South Asia, every project on time.',
  },
  {
    year: '2024',
    title: 'Robotics & Drones division launched',
    desc: 'Entered hardware with custom UAV systems and humanoid robotics for industrial clients across the Gulf region.',
  },
  {
    year: '2025',
    title: 'Global expansion',
    desc: 'Active clients in 4+ continents — US, UK, India, Middle East — with 50+ products in production and growing.',
  },
]

const principles = [
  {
    index: '01',
    title: 'Precision Engineering',
    description:
      'Every line of code is written with intent. We obsess over architecture, performance, and scalability so your product handles growth effortlessly.',
  },
  {
    index: '02',
    title: 'On-Time Delivery',
    description:
      "We\u2019ve shipped 50+ projects across 4+ continents without missing a single deadline. Timelines are commitments, not suggestions.",
  },
  {
    index: '03',
    title: 'Design-First Mindset',
    description:
      'Beautiful products win users. We blend engineering rigour with world-class UI/UX to create experiences people actually love using.',
  },
  {
    index: '04',
    title: 'Global Perspective',
    description:
      'Operating from the Middle East to Silicon Valley, we bring cross-cultural product thinking to every client engagement.',
  },
]

function useVisible(threshold = 0.08): [React.RefObject<HTMLDivElement | null>, boolean] {
  const ref = useRef<HTMLDivElement>(null)
  const [visible, setVisible] = useState(false)
  useEffect(() => {
    const obs = new IntersectionObserver(
      ([e]) => { if (e.isIntersecting) setVisible(true) },
      { threshold },
    )
    if (ref.current) obs.observe(ref.current)
    return () => obs.disconnect()
  }, [threshold])
  return [ref, visible]
}

export default function AboutPage() {
  const [heroRef,       heroVisible]       = useVisible(0.04)
  const [quoteRef,      quoteVisible]      = useVisible(0.10)
  const [servicesRef,   servicesVisible]   = useVisible(0.04)
  const [storyRef,      storyVisible]      = useVisible(0.04)
  const [principlesRef, principlesVisible] = useVisible(0.04)

  return (
    <div className="min-h-screen bg-[#fcfbff]">

      <section className="relative flex min-h-screen flex-col overflow-hidden bg-[#fcfbff] pb-0 pt-24">

        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden"
        >
          <span
            className="select-none text-[22vw] font-bold leading-none tracking-[-0.06em] text-[#7c3aed]/3"
            style={{ whiteSpace: 'nowrap' }}
          >
            ARTISTEC
          </span>
        </div>

        {/* Radial ambient glows */}
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 z-0"
          style={{
            background:
              'radial-gradient(ellipse 62% 56% at 12% 18%, rgba(215,200,251,0.42) 0%, transparent 58%), ' +
              'radial-gradient(ellipse 46% 42% at 88% 80%, rgba(197,202,245,0.32) 0%, transparent 56%)',
          }}
        />

        {/* Dot grid texture */}
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 z-0 opacity-30"
          style={{
            backgroundImage: 'radial-gradient(circle, rgba(124,58,237,0.14) 1px, transparent 1px)',
            backgroundSize: '42px 42px',
          }}
        />

        <div
          ref={heroRef}
          className="relative z-10 mx-auto flex w-full max-w-7xl flex-1 flex-col px-5 sm:px-8 md:px-12 lg:px-16 xl:px-24"
        >
          {/* Eyebrow */}
          <div
            className={cn(
              'mt-12 flex items-center gap-3',
              !heroVisible ? 'card-hidden' : 'card-animate',
            )}
          >
            <div className="h-px w-8 bg-[#c4b0f2]" />
            <span className="text-[9px] font-semibold uppercase tracking-[0.42em] text-[#7c3aed]/60">
              About Artistec
            </span>
          </div>

          {/* Giant headline */}
          <h1
            className={cn(
              'mt-7 text-[3rem] font-semibold leading-[1.02] tracking-[-0.045em] text-gray-900',
              'sm:text-[4rem] md:text-[5.2rem] lg:text-[6.2rem] xl:text-[7rem]',
              !heroVisible ? 'card-hidden' : 'card-animate',
            )}
            style={{ animationDelay: '80ms' }}
          >
            We build products
            <br />
            that{' '}
            <span className="italic text-[#a78bfa]">move the world</span>
            <br />
            forward.
          </h1>

          {/* Sub-copy + scroll cue */}
          <div
            className={cn(
              'mt-10 flex flex-wrap items-end justify-between gap-8',
              !heroVisible ? 'card-hidden' : 'card-animate',
            )}
            style={{ animationDelay: '220ms' }}
          >
            <p className="max-w-md text-[14px] leading-[1.9] text-gray-500">
              Artistec is a full-spectrum product studio — engineering web apps,
              mobile platforms, AI systems, and robotics for startups, enterprises,
              and ambitious teams across the globe.
            </p>
            <div className="flex items-center gap-2.5 text-[9px] font-semibold uppercase tracking-[0.32em] text-gray-400">
              <span>Scroll</span>
              <ArrowDown size={11} className="animate-bounce text-[#a78bfa]" />
            </div>
          </div>

          {/* Stats bar — anchored to section bottom */}
          <div
            className={cn(
              'mt-auto border-t border-[#ece8fb]',
              !heroVisible ? 'card-hidden' : 'card-animate',
            )}
            style={{ animationDelay: '380ms' }}
          >
            <div className="grid grid-cols-2 divide-x divide-[#ece8fb] lg:grid-cols-4">
              {stats.map((s) => (
                <div key={s.label} className="px-5 py-7 sm:px-8">
                  <p className="mb-0.5 text-[8.5px] font-semibold uppercase tracking-[0.32em] text-gray-400">
                    {s.index}
                  </p>
                  <p className="text-[2rem] font-semibold tracking-[-0.04em] text-[#7c3aed] sm:text-[2.5rem]">
                    {s.value}
                  </p>
                  <p className="mt-0.5 text-[11.5px] font-medium text-gray-500">{s.label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════
          MANIFESTO BAND  ·  Full-bleed quote
      ══════════════════════════════════════════ */}
      <section className="relative overflow-hidden bg-[#ece6ff] py-20 sm:py-24">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0"
          style={{
            background:
              'radial-gradient(ellipse 80% 80% at 50% 50%, rgba(167,139,250,0.15) 0%, transparent 70%)',
          }}
        />
        {/* Decorative giant opening quote */}
        <div
          aria-hidden
          className="pointer-events-none absolute left-6 top-2 select-none text-[10rem] font-bold leading-none text-[#a78bfa]/14 sm:left-12"
        >
          &ldquo;
        </div>

        <div
          ref={quoteRef}
          className="relative z-10 mx-auto max-w-5xl px-8 text-center sm:px-14 md:px-20 lg:px-24"
        >
          <p
            className={cn(
              'text-[1.35rem] font-semibold leading-[1.6] tracking-[-0.025em] text-[#3c1e8a] sm:text-[1.75rem] md:text-[2rem]',
              !quoteVisible ? 'card-hidden' : 'card-animate',
            )}
          >
            Great software should be accessible to great ideas — regardless of
            geography, team size, or budget. We don&apos;t just write code;
            we architect futures.
          </p>
          <p
            className={cn(
              'mt-6 text-[9.5px] font-semibold uppercase tracking-[0.44em] text-[#7c3aed]/55',
              !quoteVisible ? 'card-hidden' : 'card-animate',
            )}
            style={{ animationDelay: '200ms' }}
          >
            &mdash;&nbsp;Artistec &nbsp;&middot;&nbsp; Since 2022
          </p>
        </div>
      </section>

      {/* ══════════════════════════════════════════
          WHAT WE DO  ·  Asymmetric 5-col bento
      ══════════════════════════════════════════ */}
      <section className="relative bg-[#fcfbff] py-24 sm:py-32">
        <div
          ref={servicesRef}
          className="mx-auto max-w-7xl px-5 sm:px-8 md:px-12 lg:px-16 xl:px-24"
        >
          {/* Header row */}
          <div
            className={cn(
              'mb-16 flex flex-wrap items-end justify-between gap-6',
              !servicesVisible ? 'card-hidden' : 'card-animate',
            )}
          >
            <div>
              <p className="mb-3 text-[9px] font-semibold uppercase tracking-[0.4em] text-[#7c3aed]/60">
                What We Do
              </p>
              <h2 className="max-w-md text-[2rem] font-semibold leading-[1.07] tracking-[-0.04em] text-gray-900 sm:text-[2.6rem]">
                Four practice areas.
                <br />
                <span className="text-[#a78bfa]">One unified team.</span>
              </h2>
            </div>
            <Link
              href="/contact"
              className="inline-flex shrink-0 items-center gap-2 rounded-full border border-[#e0d5fb] bg-white/70 px-5 py-2.5 text-[11.5px] font-semibold text-[#6d28d9] backdrop-blur-sm transition-all duration-200 hover:border-[#c4b0f2] hover:bg-white"
            >
              Work with us <ArrowUpRight size={13} />
            </Link>
          </div>

          {/* Asymmetric grid: 01(3col)|02(2col) / 03(2col)|04(3col) */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-5">
            {services.map(({ Icon, title, description, index, span }, i) => (
              <div
                key={title}
                className={cn(
                  'group relative overflow-hidden rounded-2xl border border-[#ece8fb] bg-white/72 p-7 backdrop-blur-sm',
                  'shadow-[0_1px_4px_rgba(139,92,246,0.04),0_4px_18px_rgba(139,92,246,0.07)]',
                  'transition-all duration-300 hover:-translate-y-1 hover:border-[#d4c8f9] hover:shadow-[0_12px_44px_rgba(139,92,246,0.15)]',
                  'sm:col-span-1',
                  span,
                  !servicesVisible ? 'card-hidden' : 'card-animate',
                )}
                style={{ animationDelay: `${i * 100}ms` }}
              >
                {/* Giant faded index decoration */}
                <div
                  aria-hidden
                  className="pointer-events-none absolute right-3 top-2 select-none text-[6.5rem] font-bold leading-none tracking-[-0.05em] text-[#7c3aed]/[0.052]"
                >
                  {index}
                </div>

                {/* Icon */}
                <div className="mb-6 inline-flex h-11 w-11 items-center justify-center rounded-xl border border-[#e0d5fb] bg-[#f5f0ff] transition-all duration-300 group-hover:border-[#c4b0f2] group-hover:bg-[#ede6ff]">
                  <Icon size={18} className="text-[#7c3aed]" />
                </div>

                <p className="mb-2 text-[8.5px] font-semibold uppercase tracking-[0.34em] text-[#7c3aed]/50">
                  {index}
                </p>
                <h3 className="mb-3 text-[15px] font-semibold leading-[1.3] tracking-[-0.02em] text-gray-800">
                  {title}
                </h3>
                <p className="text-[12.5px] leading-[1.82] text-gray-500">{description}</p>

                {/* Bottom hover accent */}
                <div className="mt-6 h-px w-0 bg-[#a78bfa] transition-all duration-500 group-hover:w-full" />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════
          OUR STORY  ·  Prose + year timeline
      ══════════════════════════════════════════ */}
      <section className="relative overflow-hidden bg-[#f7f3ff] py-24 sm:py-32">
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0"
          style={{
            background:
              'radial-gradient(ellipse 55% 65% at 0% 50%, rgba(215,200,251,0.32) 0%, transparent 56%), ' +
              'radial-gradient(ellipse 45% 55% at 100% 50%, rgba(197,202,245,0.24) 0%, transparent 52%)',
          }}
        />

        <div
          ref={storyRef}
          className="relative z-10 mx-auto max-w-7xl px-5 sm:px-8 md:px-12 lg:px-16 xl:px-24"
        >
          <div className="grid gap-16 lg:grid-cols-[1fr_1px_1.15fr] lg:gap-10">

            {/* Left — prose */}
            <div className={cn(!storyVisible ? 'card-hidden' : 'card-animate')}>
              <p className="mb-4 text-[9px] font-semibold uppercase tracking-[0.4em] text-[#7c3aed]/60">
                Our Story
              </p>
              <h2 className="mb-7 text-[1.9rem] font-semibold leading-[1.12] tracking-[-0.04em] text-gray-900 sm:text-[2.4rem]">
                Built at the intersection of{' '}
                <span className="italic text-[#a78bfa]">art and technology</span>
              </h2>
              <div className="space-y-4 text-[13.5px] leading-[1.9] text-gray-500">
                <p>
                  Artistec was born from the frustration of seeing brilliant ideas
                  get stuck in mediocre execution. Our founders — engineers and
                  designers who had worked across the Gulf, Europe, and North
                  America — decided to build the studio they always wished existed.
                </p>
                <p>
                  We set up shop in Kuwait City with a small, elite team and a
                  simple promise: if you bring the vision, we&apos;ll bring the
                  velocity. Within our first year, we had shipped products used by
                  tens of thousands of people across the Middle East.
                </p>
                <p>
                  Today Artistec operates globally — delivering for clients in the
                  UAE, Saudi Arabia, India, the UK, and the US. Each project is
                  staffed by senior engineers and designers who treat your product
                  as if it were their own startup.
                </p>
              </div>

              {/* Fact chips */}
              <div className="mt-8 grid grid-cols-2 gap-3">
                {[
                  { label: 'Headquartered', value: 'Kuwait City' },
                  { label: 'Global Reach',  value: '4+ Continents' },
                  { label: 'Core Focus',    value: 'Product Engineering' },
                  { label: 'Founded',       value: '2022' },
                ].map((f) => (
                  <div
                    key={f.label}
                    className="rounded-xl border border-[#ece8fb] bg-white/60 px-4 py-3 backdrop-blur-sm"
                  >
                    <p className="text-[9px] font-semibold uppercase tracking-[0.26em] text-gray-400">
                      {f.label}
                    </p>
                    <p className="mt-0.5 text-[13px] font-semibold text-gray-800">{f.value}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Vertical divider */}
            <div className="hidden w-px bg-[#e3daf8] lg:block" />

            {/* Right — timeline */}
            <div
              className={cn(!storyVisible ? 'card-hidden' : 'card-animate')}
              style={{ animationDelay: '160ms' }}
            >
              <p className="mb-8 text-[9px] font-semibold uppercase tracking-[0.4em] text-[#7c3aed]/60">
                Timeline
              </p>
              <div>
                {milestones.map((m) => (
                  <div
                    key={m.year}
                    className="group relative flex gap-6 border-t border-[#ece8fb] py-7 last:border-b"
                  >
                    {/* Animated top-border line on hover */}
                    <div className="absolute left-0 top-0 h-px w-0 bg-[#a78bfa] transition-all duration-500 group-hover:w-full" />

                    {/* Large faded year */}
                    <div className="shrink-0 pt-0.5">
                      <span className="text-[2.1rem] font-bold tracking-[-0.05em] text-[#7c3aed]/18 transition-colors duration-300 group-hover:text-[#7c3aed]/48">
                        {m.year}
                      </span>
                    </div>

                    <div className="flex-1">
                      <p className="mb-1.5 text-[13.5px] font-semibold leading-[1.35] text-gray-800">
                        {m.title}
                      </p>
                      <p className="text-[12.5px] leading-[1.78] text-gray-500">{m.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════
          PRINCIPLES  ·  Full-width editorial rows
      ══════════════════════════════════════════ */}
      <section className="relative bg-[#fcfbff] py-24 sm:py-32">
        <div
          ref={principlesRef}
          className="mx-auto max-w-7xl px-5 sm:px-8 md:px-12 lg:px-16 xl:px-24"
        >
          <div
            className={cn('mb-16', !principlesVisible ? 'card-hidden' : 'card-animate')}
          >
            <p className="mb-3 text-[9px] font-semibold uppercase tracking-[0.4em] text-[#7c3aed]/60">
              Why Artistec
            </p>
            <h2 className="text-[2rem] font-semibold leading-[1.07] tracking-[-0.04em] text-gray-900 sm:text-[2.6rem]">
              The principles that drive
              <br />
              <span className="text-[#a78bfa]">everything we build.</span>
            </h2>
          </div>

          {/* Numbered editorial rows */}
          <div className="divide-y divide-[#ece8fb] border-t border-[#ece8fb]">
            {principles.map((p, i) => (
              <div
                key={p.index}
                className={cn(
                  'group grid grid-cols-[2.8rem_1fr] gap-x-5 gap-y-1.5 py-8 lg:grid-cols-[3.5rem_1fr_1.4fr] lg:items-start lg:py-10',
                  !principlesVisible ? 'card-hidden' : 'card-animate',
                )}
                style={{ animationDelay: `${i * 90}ms` }}
              >
                {/* Faded index */}
                <span className="pt-1 text-[1.5rem] font-bold tracking-[-0.04em] text-[#7c3aed]/16 transition-colors duration-300 group-hover:text-[#7c3aed]/42">
                  {p.index}
                </span>
                {/* Title */}
                <h3 className="pt-1 text-[1.05rem] font-semibold leading-[1.3] tracking-[-0.02em] text-gray-800">
                  {p.title}
                </h3>
                {/* Description — stacks below on mobile, 3rd col on desktop */}
                <p className="col-start-2 text-[13px] leading-[1.85] text-gray-500 lg:col-start-auto">
                  {p.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════
          CTA  ·  Dark inverted closer
      ══════════════════════════════════════════ */}
      <section
        className="relative overflow-hidden py-28 sm:py-36"
        style={{ background: '#0d0b14' }}
      >
        {/* Top glow line */}
        <div
          aria-hidden
          className="pointer-events-none absolute left-0 right-0 top-0 h-px"
          style={{
            background:
              'linear-gradient(to right, transparent, rgba(167,139,250,0.36) 40%, rgba(124,58,237,0.52) 60%, transparent)',
          }}
        />
        {/* Radial purple glow */}
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0"
          style={{
            background:
              'radial-gradient(ellipse 65% 55% at 50% 0%, rgba(124,58,237,0.17) 0%, transparent 60%)',
          }}
        />
        {/* Watermark */}
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden"
        >
          <span
            className="select-none text-[16vw] font-bold leading-none tracking-[-0.06em] text-white/[0.018]"
            style={{ whiteSpace: 'nowrap' }}
          >
            LET&apos;S BUILD
          </span>
        </div>

        <div className="relative z-10 mx-auto max-w-7xl px-5 text-center sm:px-8 md:px-12 lg:px-16 xl:px-24">
          <p className="mb-5 text-[9px] font-semibold uppercase tracking-[0.44em] text-[#a78bfa]/60">
            Let&apos;s Work Together
          </p>
          <h2 className="mb-6 text-[2.4rem] font-semibold leading-[1.05] tracking-[-0.045em] text-white sm:text-[3.2rem] md:text-[3.8rem]">
            Ready to build something
            <br />
            <span className="text-[#c4b0f2]">extraordinary?</span>
          </h2>
          <p className="mx-auto mb-12 max-w-95 text-[13.5px] leading-[1.9] text-white/38">
            From the Middle East to Silicon Valley, we design and ship products
            that cut through the noise — on time, on budget, at scale.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-3">
            <Link
              href="/contact"
              className="inline-flex items-center gap-2 rounded-full bg-white px-7 py-3.5 text-[12.5px] font-semibold text-[#17131f] shadow-[0_4px_20px_rgba(255,255,255,0.06)] transition-all duration-200 hover:bg-[#f0ebff] hover:shadow-[0_8px_36px_rgba(167,139,250,0.24)]"
            >
              Book a Strategy Call
              <ArrowUpRight size={14} />
            </Link>
            <Link
              href="/startup"
              className="inline-flex items-center gap-2 rounded-full border border-white/14 px-7 py-3.5 text-[12.5px] font-semibold text-white/70 transition-all duration-200 hover:border-white/30 hover:text-white"
            >
              Start a Project
              <ArrowUpRight size={14} />
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
